stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - data/raw/pii_dataset.csv
    - src/preprocess.py
    outs:
    - data/processed/clean_text.csv

  processbert:
    cmd: python3 src/bert_pipeline.py
    deps:
    - data/processed/clean_text.csv
    - src/bert_pipeline.py
    outs:
    - data/features/bert_tokens.pkl
